import React from 'react';

export default function PrescriptionInstructions() {
    return (
        <div className="lg:col-span-2 space-y-8">
            {/* AI Guide Card */}
            <div className="relative overflow-hidden rounded-xl bg-gradient-to-br from-primary/10 to-transparent dark:from-primary/5 dark:to-slate-900 border border-primary/20 p-6 sm:p-8">
                <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 rounded-full bg-primary/20 blur-2xl"></div>

                <div className="relative flex flex-col gap-4">
                    <div className="flex items-center gap-2 text-primary-dark dark:text-primary">
                        <span className="material-symbols-outlined">auto_awesome</span>
                        <h2 className="text-lg font-bold uppercase tracking-wide">AI Medication Guide</h2>
                    </div>

                    <p className="text-slate-700 dark:text-slate-300 text-base leading-relaxed">
                        <strong className="text-slate-900 dark:text-white">In simple terms:</strong> Amoxicillin is a penicillin antibiotic used to treat various bacterial infections, such as infections of the ears, nose, throat, urinary tract, and skin. It works by stopping the growth of bacteria.
                    </p>

                    <div className="mt-2 flex items-center gap-2 text-xs text-slate-500 dark:text-slate-500">
                        <span className="material-symbols-outlined text-[16px]">info</span>
                        <span>Generated by AI. Verify specific concerns with your doctor.</span>
                    </div>
                </div>
            </div>

            {/* Dosage & Instructions */}
            <div className="rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
                <div className="border-b border-slate-100 dark:border-slate-800 px-6 py-4">
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">Dosage &amp; Instructions</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
                    <div className="flex gap-4">
                        <div className="flex-shrink-0 flex items-center justify-center w-12 h-12 rounded-lg bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400">
                            <span className="material-symbols-outlined">schedule</span>
                        </div>
                        <div>
                            <h4 className="font-semibold text-slate-900 dark:text-white">Frequency</h4>
                            <p className="text-slate-600 dark:text-slate-400 mt-1">Take 1 capsule every 8 hours until finished.</p>
                        </div>
                    </div>
                    <div className="flex gap-4">
                        <div className="flex-shrink-0 flex items-center justify-center w-12 h-12 rounded-lg bg-orange-50 dark:bg-orange-900/20 text-orange-600 dark:text-orange-400">
                            <span className="material-symbols-outlined">restaurant</span>
                        </div>
                        <div>
                            <h4 className="font-semibold text-slate-900 dark:text-white">With Food</h4>
                            <p className="text-slate-600 dark:text-slate-400 mt-1">Take with food or milk to avoid stomach upset.</p>
                        </div>
                    </div>
                    <div className="flex gap-4">
                        <div className="flex-shrink-0 flex items-center justify-center w-12 h-12 rounded-lg bg-purple-50 dark:bg-purple-900/20 text-purple-600 dark:text-purple-400">
                            <span className="material-symbols-outlined">medication_liquid</span>
                        </div>
                        <div>
                            <h4 className="font-semibold text-slate-900 dark:text-white">Storage</h4>
                            <p className="text-slate-600 dark:text-slate-400 mt-1">Store at room temperature away from moisture.</p>
                        </div>
                    </div>
                    <div className="flex gap-4">
                        <div className="flex-shrink-0 flex items-center justify-center w-12 h-12 rounded-lg bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400">
                            <span className="material-symbols-outlined">block</span>
                        </div>
                        <div>
                            <h4 className="font-semibold text-slate-900 dark:text-white">Missed Dose</h4>
                            <p className="text-slate-600 dark:text-slate-400 mt-1">Take as soon as you remember. Do not double dose.</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Side Effects */}
            <div className="rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
                <div className="border-b border-slate-100 dark:border-slate-800 px-6 py-4 flex items-center justify-between">
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">Potential Side Effects</h3>
                    <span className="text-xs font-medium bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2 py-1 rounded">Monitor closely</span>
                </div>
                <div className="p-6">
                    <div className="space-y-4">
                        <div className="flex items-start gap-3">
                            <span className="material-symbols-outlined text-yellow-500 mt-0.5">warning</span>
                            <div>
                                <h4 className="font-medium text-slate-900 dark:text-white">Common Side Effects</h4>
                                <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">Nausea, vomiting, diarrhea, or stomach pain. These usually go away as your body adjusts.</p>
                            </div>
                        </div>
                        <div className="flex items-start gap-3">
                            <span className="material-symbols-outlined text-red-500 mt-0.5">error</span>
                            <div>
                                <h4 className="font-medium text-slate-900 dark:text-white">Serious Reactions</h4>
                                <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">Severe skin rash, itching, hives, difficulty breathing or swallowing. <span className="font-semibold text-red-600 dark:text-red-400">Seek immediate medical help.</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
